export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS';

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

export const SET_IS_LOADING_SEARCH = 'SET_IS_LOADING_SEARCH';

export const PERFORM_SEARCH = 'PERFORM_SEARCH';
